author: Matt G. Wagner
title: Matt's Personal Home Page
description: A Tampa, FL-based Software Engineer and Leadership Coach working with teams across the country

markdown: kramdown

plugins:
  - jekyll-seo-tag
